version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.13"
  jobs:
    post_create_environment:
      - asdf plugin add uv
      - asdf install uv latest
      - asdf global uv latest
    post_install:
      - uv sync --only-group doc
sphinx:
  configuration: docs/conf.py
