name: readthedocs

on:
  push:
    branches: [main]
    tags: [v3.*]

jobs:
  trigger:
    runs-on: ubuntu-24.04
    steps:
      - name: Call RTD webhook
        run: curl -X POST -d "branches=${{ github.ref_name }}" -d "token=${RTD_TOKEN}" ${RTD_WEBHOOK}
        env:
          RTD_TOKEN: ${{ secrets.RTD_TOKEN }}
          RTD_WEBHOOK: ${{ secrets.RTD_WEBHOOK }}
  
