name: test-results

on:
  workflow_run:
    workflows: ["main"]
    types:
      - completed

jobs:
  publish-test-results:
    runs-on: ubuntu-24.04
    if: github.event.workflow_run.conclusion != 'skipped'
    permissions:
      contents: read
      checks: write
      pull-requests: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
          path: artifacts
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        id: test-results
        with:
          commit: ${{ github.event.workflow_run.head_sha }}
          event_file: artifacts/event_file/event.json
          event_name: ${{ github.event.workflow_run.event }}
          files: "artifacts/**/*.xml"
      - name: Set badge color
        shell: bash
        run: |
          case ${{ fromJSON( steps.test-results.outputs.json ).conclusion }} in
            success)
              echo "BADGE_COLOR=green" >> $GITHUB_ENV
              ;;
            failure)
              echo "BADGE_COLOR=darkred" >> $GITHUB_ENV
              ;;
            neutral)
              echo "BADGE_COLOR=slategray" >> $GITHUB_ENV
              ;;
          esac
      - name: Create badge
        uses: schneegans/dynamic-badges-action@v1.7.0
        # Upload only for main branch
        if: >
          github.event_name == 'workflow_run' && github.event.workflow_run.head_branch == 'main' ||
          github.event_name != 'workflow_run' && github.ref == 'refs/heads/main'
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gistID: 5985ab4d62747586f12b0700a0107640
          filename: test_badge.json
          label: test
          message: "${{ fromJSON( steps.test-results.outputs.json ).formatted.stats.tests }} tests: ${{ fromJSON( steps.test-results.outputs.json ).conclusion }}"
          color: ${{ env.BADGE_COLOR }}
